services:
  app:
    build: .
    container_name: dc1_16_app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - FLASK_ENV=development
    volumes:
      - .:/app

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
